/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as SelectionRouteImport } from './routes/selection'
import { Route as ArtObjectIdRouteImport } from './routes/art/$objectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectionRoute = SelectionRouteImport.update({
  id: '/selection',
  path: '/selection',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtObjectIdRoute = ArtObjectIdRouteImport.update({
  id: '/art/$objectId',
  path: '/art/$objectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/departments': typeof DepartmentsRoute
  '/explore': typeof ExploreRoute
  '/selection': typeof SelectionRoute
  '/art/$objectId': typeof ArtObjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/departments': typeof DepartmentsRoute
  '/explore': typeof ExploreRoute
  '/selection': typeof SelectionRoute
  '/art/$objectId': typeof ArtObjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/departments': typeof DepartmentsRoute
  '/explore': typeof ExploreRoute
  '/selection': typeof SelectionRoute
  '/art/$objectId': typeof ArtObjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/departments'
    | '/explore'
    | '/selection'
    | '/art/$objectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/departments'
    | '/explore'
    | '/selection'
    | '/art/$objectId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/departments'
    | '/explore'
    | '/selection'
    | '/art/$objectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DepartmentsRoute: typeof DepartmentsRoute
  ExploreRoute: typeof ExploreRoute
  SelectionRoute: typeof SelectionRoute
  ArtObjectIdRoute: typeof ArtObjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selection': {
      id: '/selection'
      path: '/selection'
      fullPath: '/selection'
      preLoaderRoute: typeof SelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art/$objectId': {
      id: '/art/$objectId'
      path: '/art/$objectId'
      fullPath: '/art/$objectId'
      preLoaderRoute: typeof ArtObjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DepartmentsRoute: DepartmentsRoute,
  ExploreRoute: ExploreRoute,
  SelectionRoute: SelectionRoute,
  ArtObjectIdRoute: ArtObjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
